### ISSUE TITLE
Terraform version for Ubuntu

### ISSUE THREAD

**Issue by chippyash** [sosedoff/wireguard-aws-gateway#3]
In order to make this work for Ubuntu, I had to change the `terraform.tf` setting for the AWS provider version:
```
terraform {
  required_version = "~> 1.0"

  required_providers {
    aws = {
      version = "~> 3.63.0"
    }
  }
}
```
I've submitted a PR to add Ubuntu install instructions but have not included this change. It would be better if you could try the change on Mac and do the change. If it causes an issue, then we can add a line in the readme.

**Comment by sosedoff** [comment]
I think it should be fine, i had a local branch with:

```
terraform {
  required_version = "~> 1.1"

  // same 3.63.0 for aws
}
```

So feel free to submit a pr

**Comment by chippyash** [comment]
Can see you have updated already, so this can be closed.
